//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Code/Input/InputMapping.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Code/Input/InputMapping.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputMapping: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputMapping()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputMapping"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""c234a768-90ec-41ea-919b-4dc073c00c5f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3dc776c1-a103-4522-8f63-668f13a7ff3f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NormalAtk"",
                    ""type"": ""Button"",
                    ""id"": ""1935a002-6654-4d1d-8ed6-557466decee6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlowDown"",
                    ""type"": ""Button"",
                    ""id"": ""d1003102-7779-4429-bd40-ffbb98fb08f2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2c3ff33c-2cd6-4d9a-ba40-ea68807125e8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cfe30cc9-113a-46ad-9824-e45fae7cf967"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""be059124-8e81-4d00-aecb-ab3cc6d746ff"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""57a11563-d4fa-4fd0-a23b-fecfe575ca06"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8d6c0ce7-3639-4d8d-a089-ecaa9e938b47"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9ddc0316-85c9-4993-84c9-dd5d4efa1c7f"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalAtk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7646ac08-1451-4d41-8663-cbafb6a795c6"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TestAtk"",
            ""id"": ""a136bd23-c8f3-4d82-948c-051d3552315b"",
            ""actions"": [
                {
                    ""name"": ""ATKButton"",
                    ""type"": ""Button"",
                    ""id"": ""241ac7e6-eeb5-467f-a8d6-5b135f21dd54"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4961e2b4-0a14-4359-b149-cb8d962a9e84"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e6958fd-103f-4ab3-bfc6-c37cf5ddf154"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07bb501b-3d45-4fd5-ab9d-5dc69d7b8192"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d33f7c43-c8cf-4124-8747-5bc073840a64"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CureAtk"",
            ""id"": ""84812aaa-ad46-4bd0-9902-46c2a4cab5db"",
            ""actions"": [
                {
                    ""name"": ""ATKButton"",
                    ""type"": ""Button"",
                    ""id"": ""5abd737f-22ec-46ca-b7a3-f6a6c9093cd5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""54dce748-e31b-4f75-bfa6-2fa22195166d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8528c43f-22fe-481b-b5e7-24c2eeb411a0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caf4f065-e62d-47cb-85c8-1e8a7866008c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37afc559-746d-41e8-a21f-d8eba438da5c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a8adaa4-5828-43a9-8b19-a04daf262e36"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""205dda04-067e-49dc-b0fb-d774bed9f880"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATKButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""AttackToggle"",
            ""id"": ""0ee62a7c-d600-4673-b081-e8783dee92e9"",
            ""actions"": [
                {
                    ""name"": ""TestAtkToggle"",
                    ""type"": ""Button"",
                    ""id"": ""0b225b91-80ed-48be-86e9-05ecc8032a9d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3f995c85-d91a-4cc1-864a-bcb040477639"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestAtkToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CureToggle"",
            ""id"": ""f802a2c3-b3a5-400b-9c44-03ab0d595315"",
            ""actions"": [
                {
                    ""name"": ""TestAtkToggle"",
                    ""type"": ""Button"",
                    ""id"": ""2aaf215f-f028-4757-9e78-acd7f9318e1c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CureAtkToggle"",
                    ""type"": ""Button"",
                    ""id"": ""2ddce766-42f4-4c27-a510-aadb7265b564"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CureAtkToggle1"",
                    ""type"": ""Button"",
                    ""id"": ""685ac207-79ad-49ab-a599-7678d1520b7c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b1bad5c-104c-470e-9503-81c1a82e86ab"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestAtkToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f1b0e01-20c4-4bb8-9a8e-566c80dd2590"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CureAtkToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a345ebe-5abb-4694-b622-790b1c50b720"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CureAtkToggle1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SettingMenu"",
            ""id"": ""65dba860-3b04-40fe-8caf-9051af77807a"",
            ""actions"": [
                {
                    ""name"": ""ESC"",
                    ""type"": ""Button"",
                    ""id"": ""87f923e9-49f1-4ffb-9f00-d5c8b834e7ee"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8a5a3a36-6744-4514-afbe-a8abbaf59264"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""78dbecdc-e1ee-42a4-94d1-da5561f2c299"",
            ""actions"": [
                {
                    ""name"": ""FillEnergy"",
                    ""type"": ""Button"",
                    ""id"": ""40469789-9aea-4a00-a4e3-b1d881793d12"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FillHP"",
                    ""type"": ""Button"",
                    ""id"": ""caa19696-5f2c-42bc-9e91-79a17f34b44c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d2866462-dc92-4ea1-89b5-e2127ce0388d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FillEnergy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f025444-403d-474c-8998-19c0fc1c7506"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FillHP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_NormalAtk = m_Player.FindAction("NormalAtk", throwIfNotFound: true);
        m_Player_SlowDown = m_Player.FindAction("SlowDown", throwIfNotFound: true);
        // TestAtk
        m_TestAtk = asset.FindActionMap("TestAtk", throwIfNotFound: true);
        m_TestAtk_ATKButton = m_TestAtk.FindAction("ATKButton", throwIfNotFound: true);
        // CureAtk
        m_CureAtk = asset.FindActionMap("CureAtk", throwIfNotFound: true);
        m_CureAtk_ATKButton = m_CureAtk.FindAction("ATKButton", throwIfNotFound: true);
        // AttackToggle
        m_AttackToggle = asset.FindActionMap("AttackToggle", throwIfNotFound: true);
        m_AttackToggle_TestAtkToggle = m_AttackToggle.FindAction("TestAtkToggle", throwIfNotFound: true);
        // CureToggle
        m_CureToggle = asset.FindActionMap("CureToggle", throwIfNotFound: true);
        m_CureToggle_TestAtkToggle = m_CureToggle.FindAction("TestAtkToggle", throwIfNotFound: true);
        m_CureToggle_CureAtkToggle = m_CureToggle.FindAction("CureAtkToggle", throwIfNotFound: true);
        m_CureToggle_CureAtkToggle1 = m_CureToggle.FindAction("CureAtkToggle1", throwIfNotFound: true);
        // SettingMenu
        m_SettingMenu = asset.FindActionMap("SettingMenu", throwIfNotFound: true);
        m_SettingMenu_ESC = m_SettingMenu.FindAction("ESC", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_FillEnergy = m_Debug.FindAction("FillEnergy", throwIfNotFound: true);
        m_Debug_FillHP = m_Debug.FindAction("FillHP", throwIfNotFound: true);
    }

    ~@InputMapping()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, InputMapping.Player.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TestAtk.enabled, "This will cause a leak and performance issues, InputMapping.TestAtk.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CureAtk.enabled, "This will cause a leak and performance issues, InputMapping.CureAtk.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_AttackToggle.enabled, "This will cause a leak and performance issues, InputMapping.AttackToggle.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CureToggle.enabled, "This will cause a leak and performance issues, InputMapping.CureToggle.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_SettingMenu.enabled, "This will cause a leak and performance issues, InputMapping.SettingMenu.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Debug.enabled, "This will cause a leak and performance issues, InputMapping.Debug.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_NormalAtk;
    private readonly InputAction m_Player_SlowDown;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @InputMapping m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Player_Move;
        /// <summary>
        /// Provides access to the underlying input action "Player/NormalAtk".
        /// </summary>
        public InputAction @NormalAtk => m_Wrapper.m_Player_NormalAtk;
        /// <summary>
        /// Provides access to the underlying input action "Player/SlowDown".
        /// </summary>
        public InputAction @SlowDown => m_Wrapper.m_Player_SlowDown;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @NormalAtk.started += instance.OnNormalAtk;
            @NormalAtk.performed += instance.OnNormalAtk;
            @NormalAtk.canceled += instance.OnNormalAtk;
            @SlowDown.started += instance.OnSlowDown;
            @SlowDown.performed += instance.OnSlowDown;
            @SlowDown.canceled += instance.OnSlowDown;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @NormalAtk.started -= instance.OnNormalAtk;
            @NormalAtk.performed -= instance.OnNormalAtk;
            @NormalAtk.canceled -= instance.OnNormalAtk;
            @SlowDown.started -= instance.OnSlowDown;
            @SlowDown.performed -= instance.OnSlowDown;
            @SlowDown.canceled -= instance.OnSlowDown;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);

    // TestAtk
    private readonly InputActionMap m_TestAtk;
    private List<ITestAtkActions> m_TestAtkActionsCallbackInterfaces = new List<ITestAtkActions>();
    private readonly InputAction m_TestAtk_ATKButton;
    /// <summary>
    /// Provides access to input actions defined in input action map "TestAtk".
    /// </summary>
    public struct TestAtkActions
    {
        private @InputMapping m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TestAtkActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "TestAtk/ATKButton".
        /// </summary>
        public InputAction @ATKButton => m_Wrapper.m_TestAtk_ATKButton;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_TestAtk; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TestAtkActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TestAtkActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TestAtkActions" />
        public void AddCallbacks(ITestAtkActions instance)
        {
            if (instance == null || m_Wrapper.m_TestAtkActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TestAtkActionsCallbackInterfaces.Add(instance);
            @ATKButton.started += instance.OnATKButton;
            @ATKButton.performed += instance.OnATKButton;
            @ATKButton.canceled += instance.OnATKButton;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TestAtkActions" />
        private void UnregisterCallbacks(ITestAtkActions instance)
        {
            @ATKButton.started -= instance.OnATKButton;
            @ATKButton.performed -= instance.OnATKButton;
            @ATKButton.canceled -= instance.OnATKButton;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TestAtkActions.UnregisterCallbacks(ITestAtkActions)" />.
        /// </summary>
        /// <seealso cref="TestAtkActions.UnregisterCallbacks(ITestAtkActions)" />
        public void RemoveCallbacks(ITestAtkActions instance)
        {
            if (m_Wrapper.m_TestAtkActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TestAtkActions.AddCallbacks(ITestAtkActions)" />
        /// <seealso cref="TestAtkActions.RemoveCallbacks(ITestAtkActions)" />
        /// <seealso cref="TestAtkActions.UnregisterCallbacks(ITestAtkActions)" />
        public void SetCallbacks(ITestAtkActions instance)
        {
            foreach (var item in m_Wrapper.m_TestAtkActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TestAtkActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TestAtkActions" /> instance referencing this action map.
    /// </summary>
    public TestAtkActions @TestAtk => new TestAtkActions(this);

    // CureAtk
    private readonly InputActionMap m_CureAtk;
    private List<ICureAtkActions> m_CureAtkActionsCallbackInterfaces = new List<ICureAtkActions>();
    private readonly InputAction m_CureAtk_ATKButton;
    /// <summary>
    /// Provides access to input actions defined in input action map "CureAtk".
    /// </summary>
    public struct CureAtkActions
    {
        private @InputMapping m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CureAtkActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CureAtk/ATKButton".
        /// </summary>
        public InputAction @ATKButton => m_Wrapper.m_CureAtk_ATKButton;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CureAtk; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CureAtkActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CureAtkActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CureAtkActions" />
        public void AddCallbacks(ICureAtkActions instance)
        {
            if (instance == null || m_Wrapper.m_CureAtkActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CureAtkActionsCallbackInterfaces.Add(instance);
            @ATKButton.started += instance.OnATKButton;
            @ATKButton.performed += instance.OnATKButton;
            @ATKButton.canceled += instance.OnATKButton;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CureAtkActions" />
        private void UnregisterCallbacks(ICureAtkActions instance)
        {
            @ATKButton.started -= instance.OnATKButton;
            @ATKButton.performed -= instance.OnATKButton;
            @ATKButton.canceled -= instance.OnATKButton;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CureAtkActions.UnregisterCallbacks(ICureAtkActions)" />.
        /// </summary>
        /// <seealso cref="CureAtkActions.UnregisterCallbacks(ICureAtkActions)" />
        public void RemoveCallbacks(ICureAtkActions instance)
        {
            if (m_Wrapper.m_CureAtkActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CureAtkActions.AddCallbacks(ICureAtkActions)" />
        /// <seealso cref="CureAtkActions.RemoveCallbacks(ICureAtkActions)" />
        /// <seealso cref="CureAtkActions.UnregisterCallbacks(ICureAtkActions)" />
        public void SetCallbacks(ICureAtkActions instance)
        {
            foreach (var item in m_Wrapper.m_CureAtkActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CureAtkActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CureAtkActions" /> instance referencing this action map.
    /// </summary>
    public CureAtkActions @CureAtk => new CureAtkActions(this);

    // AttackToggle
    private readonly InputActionMap m_AttackToggle;
    private List<IAttackToggleActions> m_AttackToggleActionsCallbackInterfaces = new List<IAttackToggleActions>();
    private readonly InputAction m_AttackToggle_TestAtkToggle;
    /// <summary>
    /// Provides access to input actions defined in input action map "AttackToggle".
    /// </summary>
    public struct AttackToggleActions
    {
        private @InputMapping m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public AttackToggleActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "AttackToggle/TestAtkToggle".
        /// </summary>
        public InputAction @TestAtkToggle => m_Wrapper.m_AttackToggle_TestAtkToggle;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_AttackToggle; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="AttackToggleActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(AttackToggleActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="AttackToggleActions" />
        public void AddCallbacks(IAttackToggleActions instance)
        {
            if (instance == null || m_Wrapper.m_AttackToggleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AttackToggleActionsCallbackInterfaces.Add(instance);
            @TestAtkToggle.started += instance.OnTestAtkToggle;
            @TestAtkToggle.performed += instance.OnTestAtkToggle;
            @TestAtkToggle.canceled += instance.OnTestAtkToggle;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="AttackToggleActions" />
        private void UnregisterCallbacks(IAttackToggleActions instance)
        {
            @TestAtkToggle.started -= instance.OnTestAtkToggle;
            @TestAtkToggle.performed -= instance.OnTestAtkToggle;
            @TestAtkToggle.canceled -= instance.OnTestAtkToggle;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="AttackToggleActions.UnregisterCallbacks(IAttackToggleActions)" />.
        /// </summary>
        /// <seealso cref="AttackToggleActions.UnregisterCallbacks(IAttackToggleActions)" />
        public void RemoveCallbacks(IAttackToggleActions instance)
        {
            if (m_Wrapper.m_AttackToggleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="AttackToggleActions.AddCallbacks(IAttackToggleActions)" />
        /// <seealso cref="AttackToggleActions.RemoveCallbacks(IAttackToggleActions)" />
        /// <seealso cref="AttackToggleActions.UnregisterCallbacks(IAttackToggleActions)" />
        public void SetCallbacks(IAttackToggleActions instance)
        {
            foreach (var item in m_Wrapper.m_AttackToggleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AttackToggleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="AttackToggleActions" /> instance referencing this action map.
    /// </summary>
    public AttackToggleActions @AttackToggle => new AttackToggleActions(this);

    // CureToggle
    private readonly InputActionMap m_CureToggle;
    private List<ICureToggleActions> m_CureToggleActionsCallbackInterfaces = new List<ICureToggleActions>();
    private readonly InputAction m_CureToggle_TestAtkToggle;
    private readonly InputAction m_CureToggle_CureAtkToggle;
    private readonly InputAction m_CureToggle_CureAtkToggle1;
    /// <summary>
    /// Provides access to input actions defined in input action map "CureToggle".
    /// </summary>
    public struct CureToggleActions
    {
        private @InputMapping m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CureToggleActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CureToggle/TestAtkToggle".
        /// </summary>
        public InputAction @TestAtkToggle => m_Wrapper.m_CureToggle_TestAtkToggle;
        /// <summary>
        /// Provides access to the underlying input action "CureToggle/CureAtkToggle".
        /// </summary>
        public InputAction @CureAtkToggle => m_Wrapper.m_CureToggle_CureAtkToggle;
        /// <summary>
        /// Provides access to the underlying input action "CureToggle/CureAtkToggle1".
        /// </summary>
        public InputAction @CureAtkToggle1 => m_Wrapper.m_CureToggle_CureAtkToggle1;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CureToggle; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CureToggleActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CureToggleActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CureToggleActions" />
        public void AddCallbacks(ICureToggleActions instance)
        {
            if (instance == null || m_Wrapper.m_CureToggleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CureToggleActionsCallbackInterfaces.Add(instance);
            @TestAtkToggle.started += instance.OnTestAtkToggle;
            @TestAtkToggle.performed += instance.OnTestAtkToggle;
            @TestAtkToggle.canceled += instance.OnTestAtkToggle;
            @CureAtkToggle.started += instance.OnCureAtkToggle;
            @CureAtkToggle.performed += instance.OnCureAtkToggle;
            @CureAtkToggle.canceled += instance.OnCureAtkToggle;
            @CureAtkToggle1.started += instance.OnCureAtkToggle1;
            @CureAtkToggle1.performed += instance.OnCureAtkToggle1;
            @CureAtkToggle1.canceled += instance.OnCureAtkToggle1;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CureToggleActions" />
        private void UnregisterCallbacks(ICureToggleActions instance)
        {
            @TestAtkToggle.started -= instance.OnTestAtkToggle;
            @TestAtkToggle.performed -= instance.OnTestAtkToggle;
            @TestAtkToggle.canceled -= instance.OnTestAtkToggle;
            @CureAtkToggle.started -= instance.OnCureAtkToggle;
            @CureAtkToggle.performed -= instance.OnCureAtkToggle;
            @CureAtkToggle.canceled -= instance.OnCureAtkToggle;
            @CureAtkToggle1.started -= instance.OnCureAtkToggle1;
            @CureAtkToggle1.performed -= instance.OnCureAtkToggle1;
            @CureAtkToggle1.canceled -= instance.OnCureAtkToggle1;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CureToggleActions.UnregisterCallbacks(ICureToggleActions)" />.
        /// </summary>
        /// <seealso cref="CureToggleActions.UnregisterCallbacks(ICureToggleActions)" />
        public void RemoveCallbacks(ICureToggleActions instance)
        {
            if (m_Wrapper.m_CureToggleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CureToggleActions.AddCallbacks(ICureToggleActions)" />
        /// <seealso cref="CureToggleActions.RemoveCallbacks(ICureToggleActions)" />
        /// <seealso cref="CureToggleActions.UnregisterCallbacks(ICureToggleActions)" />
        public void SetCallbacks(ICureToggleActions instance)
        {
            foreach (var item in m_Wrapper.m_CureToggleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CureToggleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CureToggleActions" /> instance referencing this action map.
    /// </summary>
    public CureToggleActions @CureToggle => new CureToggleActions(this);

    // SettingMenu
    private readonly InputActionMap m_SettingMenu;
    private List<ISettingMenuActions> m_SettingMenuActionsCallbackInterfaces = new List<ISettingMenuActions>();
    private readonly InputAction m_SettingMenu_ESC;
    /// <summary>
    /// Provides access to input actions defined in input action map "SettingMenu".
    /// </summary>
    public struct SettingMenuActions
    {
        private @InputMapping m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SettingMenuActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "SettingMenu/ESC".
        /// </summary>
        public InputAction @ESC => m_Wrapper.m_SettingMenu_ESC;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_SettingMenu; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SettingMenuActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SettingMenuActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SettingMenuActions" />
        public void AddCallbacks(ISettingMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_SettingMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SettingMenuActionsCallbackInterfaces.Add(instance);
            @ESC.started += instance.OnESC;
            @ESC.performed += instance.OnESC;
            @ESC.canceled += instance.OnESC;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SettingMenuActions" />
        private void UnregisterCallbacks(ISettingMenuActions instance)
        {
            @ESC.started -= instance.OnESC;
            @ESC.performed -= instance.OnESC;
            @ESC.canceled -= instance.OnESC;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SettingMenuActions.UnregisterCallbacks(ISettingMenuActions)" />.
        /// </summary>
        /// <seealso cref="SettingMenuActions.UnregisterCallbacks(ISettingMenuActions)" />
        public void RemoveCallbacks(ISettingMenuActions instance)
        {
            if (m_Wrapper.m_SettingMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SettingMenuActions.AddCallbacks(ISettingMenuActions)" />
        /// <seealso cref="SettingMenuActions.RemoveCallbacks(ISettingMenuActions)" />
        /// <seealso cref="SettingMenuActions.UnregisterCallbacks(ISettingMenuActions)" />
        public void SetCallbacks(ISettingMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_SettingMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SettingMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SettingMenuActions" /> instance referencing this action map.
    /// </summary>
    public SettingMenuActions @SettingMenu => new SettingMenuActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private List<IDebugActions> m_DebugActionsCallbackInterfaces = new List<IDebugActions>();
    private readonly InputAction m_Debug_FillEnergy;
    private readonly InputAction m_Debug_FillHP;
    /// <summary>
    /// Provides access to input actions defined in input action map "Debug".
    /// </summary>
    public struct DebugActions
    {
        private @InputMapping m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public DebugActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Debug/FillEnergy".
        /// </summary>
        public InputAction @FillEnergy => m_Wrapper.m_Debug_FillEnergy;
        /// <summary>
        /// Provides access to the underlying input action "Debug/FillHP".
        /// </summary>
        public InputAction @FillHP => m_Wrapper.m_Debug_FillHP;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="DebugActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="DebugActions" />
        public void AddCallbacks(IDebugActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugActionsCallbackInterfaces.Add(instance);
            @FillEnergy.started += instance.OnFillEnergy;
            @FillEnergy.performed += instance.OnFillEnergy;
            @FillEnergy.canceled += instance.OnFillEnergy;
            @FillHP.started += instance.OnFillHP;
            @FillHP.performed += instance.OnFillHP;
            @FillHP.canceled += instance.OnFillHP;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="DebugActions" />
        private void UnregisterCallbacks(IDebugActions instance)
        {
            @FillEnergy.started -= instance.OnFillEnergy;
            @FillEnergy.performed -= instance.OnFillEnergy;
            @FillEnergy.canceled -= instance.OnFillEnergy;
            @FillHP.started -= instance.OnFillHP;
            @FillHP.performed -= instance.OnFillHP;
            @FillHP.canceled -= instance.OnFillHP;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DebugActions.UnregisterCallbacks(IDebugActions)" />.
        /// </summary>
        /// <seealso cref="DebugActions.UnregisterCallbacks(IDebugActions)" />
        public void RemoveCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="DebugActions.AddCallbacks(IDebugActions)" />
        /// <seealso cref="DebugActions.RemoveCallbacks(IDebugActions)" />
        /// <seealso cref="DebugActions.UnregisterCallbacks(IDebugActions)" />
        public void SetCallbacks(IDebugActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="DebugActions" /> instance referencing this action map.
    /// </summary>
    public DebugActions @Debug => new DebugActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NormalAtk" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNormalAtk(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SlowDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSlowDown(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "TestAtk" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TestAtkActions.AddCallbacks(ITestAtkActions)" />
    /// <seealso cref="TestAtkActions.RemoveCallbacks(ITestAtkActions)" />
    public interface ITestAtkActions
    {
        /// <summary>
        /// Method invoked when associated input action "ATKButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnATKButton(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CureAtk" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CureAtkActions.AddCallbacks(ICureAtkActions)" />
    /// <seealso cref="CureAtkActions.RemoveCallbacks(ICureAtkActions)" />
    public interface ICureAtkActions
    {
        /// <summary>
        /// Method invoked when associated input action "ATKButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnATKButton(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "AttackToggle" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="AttackToggleActions.AddCallbacks(IAttackToggleActions)" />
    /// <seealso cref="AttackToggleActions.RemoveCallbacks(IAttackToggleActions)" />
    public interface IAttackToggleActions
    {
        /// <summary>
        /// Method invoked when associated input action "TestAtkToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestAtkToggle(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CureToggle" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CureToggleActions.AddCallbacks(ICureToggleActions)" />
    /// <seealso cref="CureToggleActions.RemoveCallbacks(ICureToggleActions)" />
    public interface ICureToggleActions
    {
        /// <summary>
        /// Method invoked when associated input action "TestAtkToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestAtkToggle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CureAtkToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCureAtkToggle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CureAtkToggle1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCureAtkToggle1(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "SettingMenu" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SettingMenuActions.AddCallbacks(ISettingMenuActions)" />
    /// <seealso cref="SettingMenuActions.RemoveCallbacks(ISettingMenuActions)" />
    public interface ISettingMenuActions
    {
        /// <summary>
        /// Method invoked when associated input action "ESC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnESC(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Debug" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="DebugActions.AddCallbacks(IDebugActions)" />
    /// <seealso cref="DebugActions.RemoveCallbacks(IDebugActions)" />
    public interface IDebugActions
    {
        /// <summary>
        /// Method invoked when associated input action "FillEnergy" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFillEnergy(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FillHP" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFillHP(InputAction.CallbackContext context);
    }
}
